package cairn

var (
	backgrounds = []string{
		"aurifex",
		"barber-surgeon",
		"beast handler",
		"bonekeeper",
		"cutpurse",
		"fieldwarden",
		"fletchwind",
		"foundling",
		"fungal forager",
		"greenwise",
		"half witch",
		"hexenbane",
		"jongleur",
		"kettlewright",
		"marchguard",
		"mountebank",
		"outrider",
		"prowler",
		"rill runner",
		"scrivener",
	}

	names = map[string][]string{
		"aurifex":        {"Hestia", "Basil", "Rune", "Prism", "Ember", "Quintess", "Aludel", "Mordant", "Salaman", "Jazia"},
		"barber-surgeon": {"Wilmot", "Patch", "Lancet", "Sawbones", "Theo", "Cutwell", "Humor", "Landsford", "Goodeye", "Johanna"},
		"beast handler":  {"Amara", "Wulf", "Mireille", "Soren", "Freki", "Aster", "Gerrik", "Boreas", "Delphine", "Matheus"},
		"bonekeeper":     {"Rook", "Ebon", "Moro", "Yew", "Pall", "Leth", "Nix", "Barnaby", "Vesper", "Leder"},
		"cutpurse":       {"Sable", "Lyra", "Eamon", "Salina", "Elara", "Freya", "Isolde", "Sparrow", "Ivy", "Silas"},
		"fieldwarden":    {"Seed", "Thresh", "Dibber", "Sow", "Stalk", "Harrow", "Cobb", "Flax", "Briar", "Rye"},
		"fletchwind":     {"Flint", "Feather", "Crier", "Thunder", "Falcon", "Pluck", "Needle", "Warsong", "Hawk", "Cai"},
		"foundling":      {"Faunus", "Snowdrop", "Wisp", "Silverdew", "Brim", "Solstice", "Steeleye", "Sileas", "Gossamer", "Hazel"},
		"fungal forager": {"Unther", "Woozy", "Hilda", "Current", "Leif", "Ratan", "Mourella", "Lal", "Per", "Madrigal"},
		"greenwise":      {"Briar", "Moss", "Fern", "Lichen", "Root", "Willow", "Sage", "Yarrow", "Rowan", "Ash"},
		"half witch":     {"Solena", "Veles", "Bryn", "Sabine", "Razvan", "Rowena", "Galen", "Nyx", "Vex", "Iwan"},
		"hexenbane":      {"Percival", "Felix", "Isolde", "Wolfram", "Aldric", "Eira", "Oswin", "Ivor", "Brunhilda", "Beatrix"},
		"jongleur":       {"Jax", "Selene", "Baladria", "Ada", "Felix", "Saylor", "Tripp", "Lantos", "Echo", "Jubilo"},
		"kettlewright":   {"Fergus", "Eamon", "Bram", "Idris", "Elara", "Darragh", "Seren", "Rónán", "Berek", "Lorenz"},
		"marchguard":     {"Gann", "Light", "Gale", "Frost", "Thorn", "Reed", "Flint", "Brook", "Brie", "Aasim"},
		"mountebank":     {"Ambrose", "Lucius", "Beauregard", "Cornelius", "Aria", "Seren", "Indigo", "Delphine", "Solene", "Noa"},
		"outrider":       {"Drake", "Cyra", "Keir", "Darius", "Valen", "Rorik", "Yara", "Rui", "Talon", "Jory"},
		"prowler":        {"Winda", "Brielle", "Theron", "Chayse", "Nuja", "Dev", "Raven", "Lyra", "Sable"},
		"rill runner":    {"Gale", "Piper", "Brook", "Adair", "Stone", "Dale", "Wren", "Cliff", "Rain", "Robin"},
		"scrivener":      {"Per", "Stilo", "Akshara", "Pisa", "Ji-Yun", "Kalamos", "Hugo", "Shui", "Kalam", "Julius"},
	}

	traits = [][]string{
		{"athletic", "brawny", "flabby", "lanky", "rugged", "scrawny", "short", "statuesque", "stout", "towering"},
		{"birthmarked", "webbed", "scarred", "marked", "rosy", "soft", "tanned", "tattooed", "tight", "weathered"},
		{"bald", "braided", "curly", "filthy", "frizzy", "long", "luxurious", "oily", "wavy", "wispy"},
		{"bony", "broken", "chiseled", "elongated", "pale", "perfect", "rat-like", "sharp", "square", "sunken"},
		{"blunt", "booming", "cryptic", "droning", "formal", "gravelly", "precise", "squeaky", "stuttering", "whispery"},
		{"antique", "bloody", "elegant", "filthy", "foreign", "frayed", "frumpy", "livery", "rancid", "soiled"},
		{"ambitious", "cautious", "courageous", "disciplined", "gregarious", "honorable", "humble", "merciful", "serene", "tolerant"},
		{"aggressive", "bitter", "craven", "deceitful", "greedy", "lazy", "nervous", "rude", "vain", "vengeful"},
	}

	bondsList = []string{
		"You inherited a Single Gem (500gp, cold and brittle) from a long-dead relative. It arrived with a warning: squander your newfound riches and a debt long thought forgotten would be called.",
		"A distant cousin left you a small inheritance. Take 20Gp, and an Ornate Compass that always points towards something deep in The Woods.",
		"You carry a Portrait in a locket (petty) of a past love who disappeared into The Woods long ago. Somehow, you know that they are still alive.",
		"You found a Tiny Crystal Prism (petty) buried in the dirt. When held up to the light, it shows visions of an unknown location deep within The Woods. Sometimes, you feel a presence looking back at you.",
		"You once freed a Naiad from a choked stream. In return, it gave you some Silver Moss. Swallow it near water and the creature will come, once, to repay its debt.",
		"You inherited an old Journal, bound in bark. Each evening, its pages are filled with the events of the day, crassly from the journal’s perspective. The writing is crude, but accurate.",
		"You protect a long-dormant family secret. Take one half of an Ancient Key (petty). They say that if joined with its twin, it opens a Gate through any door.",
		"You received a Letter (petty) detailing incontrovertible proof that your true parentage is that of Fae nobility.The note also indicates a date and location where you are to meet them, deep in the The Woods.",
		"You owe a great debt to a member of the nobility, and carry their Signet Ring (petty), which serves as proof of their protection as well as your obligation.",
		"You consumed a Mischievous Spirit that periodically wreaks havoc on your insides, demanding to be taken home. It wants to keep you alive, at least until it is free. It takes up one slot, but eats one Fatigue per day. It can detect magic and knows a bit about The Woods.",
		"A roaming storyteller once spun you tales of great treasure hidden deep in The Woods. You thought it naught but fancy, till they gave you A Rolled-Up Map (petty) marked with an X.",
		"During your travels, you met a dying hunter who asked you to deliver a message to their loved ones. Take a Letter (petty), sealed with tree sap. It is addressed only to the Lord Of Winter.",
		"You found a wounded beast in the forest, but chose to ignore it. You see it everywhere now, but only when you’re alone. It looks sad, but not angry.",
		"You promised a childhood friend that you’d bring them back a rare gift, something unique in all the world. Take a Bracelet (petty) woven from twine and wildflowers.",
		"You crossed a creature of The Woods, and it cursed you with a Stone Heart (1 Armor, bulky). With each passing month, the stone grows heavier by one slot. Until your debt is lifted, you cannot truly die.",
		"You carved a Whistle (petty) from an Oak Lord’s branch. Your act did not go unnoticed. You cannot seem to rid yourself of the whistle either.",
		"The Dawn Brigade did your family a service, giving you a dried Blood-Red Flower (petty) as proof. When the flower turns white, it means the favor is owed.",
		"An entertainer once visited your home, filling it with story and song. He left one day without a word, leaving behind only A Miniature Lute. Something rattles inside.",
		"A white crow appeared to you in a dream, holding a twig in its mouth. You awoke the next morning with The Twig (petty) in your hand. You believe it brings you luck. It smells faintly of sulfur.",
		"One of your ancestors wronged a Moss Witch, who cursed their bloodline. Your visage causes mirrors to shatter. You’ve noticed that the shards can sometimes reveal illusions.",
	}

	omensList = []string{
		"The once rich waters of a life-giving river have turned black and putrid, tainting the land and sickening those who drink from it. A village elder points to some recent desecration as the cause, but most do not heed their words.",
		"It feels like winter has arrived too quickly this year, frost and snows making their appearance much earlier than expected. There is talk of a pattern to the frost found in windows, ponds, and cracks in the ground. It almost looks like a map.",
		"A thick, unnatural fog has begun encroaching upon an ancient and holy grove. It is said to be the work of a great forest spirit, angered by nearby deforestation.",
		"The night sky grows dimmer each evening, as if stars are disappearing one by one. Rumors of hellish creatures capturing farmers and pulling them into The Roots are spreading like wildfire. Village elders believe the two are connected.",
		"The songbirds of The Woods have fallen eerily silent as of late. Hunters claim that a spectral figure has been spotted wandering the forest, gazing longingly at anyone it encounters.",
		"Strange, tear-shaped stones have been found throughout the region, sparking a “gold rush” of sorts for jewelers and thieves alike. The locals believe they are the tears of the earth itself, weeping for a great tragedy yet to come.",
		"Swarming pests gnaw away at the edges of dreams, and farmers speak of a loud buzzing sound emanating from deep within The Woods. They also say that the sound is getting closer.",
		"There is a village known far and wide for its impressive “mother tree”, said to shelter the town’s secrets in its boughs. Recently, it has begun bleeding red sap, worrying the elders.",
		"The moon turns a deep crimson, bathing the night in an eerie, blood-red light. Some say it heralds a time of chaos and strife, as the boundaries between The Woods and the mortal realm grow thin.",
		"Strange cracks have appeared in the night sky, revealing a swirling vortex of light and color. Some say that the divide between realms is at its weakest in centuries, and fear what may emerge from the other side.",
		"A night-blooming flower once thought extinct is sprouting up throughout The Woods. Its scent is intoxicating, but also causes vivid nightmares.",
		"Local livestock have grown increasingly agitated and unmanageable as of late. An old shephard says it is due to an unsettling howl that emanates from The Woods each full moon.",
		"Swarms of insects are fleeing from The Woods in droves, destroying any wooden structures they come across. The sound of their wings hum a familiar tune as they pass overhead, like a forgotten nursery rhyme.",
		"Hunters talk of a curse that befalls any who kill a white-frocked beast: soon after, they are found dead in their homes. Each day, there are fewer and fewer creatures to hunt.",
		"Folks say that a faint laughter can be heard echoing out of wells all over the city. At night, they say the echoes change to sobs.",
		"The constellations have slowly started shifting in the night sky, forming unfamiliar patterns that have stargazers and sages perplexed. Even the animals seem disturbed.",
		"An ancient tree at the heart of a sleepy village has suddenly withered and died, despite showing no signs of disease. After its trunk was cut, a bloody hand was found in its core.",
		"Statues have been weeping blood for months on end, and the wombs of the village have lain barren since they began to fall. A single child has been the only exception, taken by elders overcome with fear and dread.",
		"The local fauna is behaving oddly, displaying heightened aggression, or fleeing the area entirely. Hunters talk of a shadowy figure that roams The Woods, calling to the animals.",
		"Border towns have become riotous in recent weeks, after multiple claims of a red-robed figure appearing in their children’s dreams, uttering the same warning: A fire is coming, and it will consume them all.",
	}

	backgroundDetails = map[string]string{
		"aurifex":        "You are an artisan of the arcane, a smith of subtle forces. In the crucible of your workshop, the laws that govern this world are warped to suit your needs.",
		"barber-surgeon": "You walk the line between healer and harrower, knowing the frailty of the flesh but also the secrets that lay within. With the right tools, life and death are merely words.",
		"beast handler":  "You alone can walk among the creatures of the wild, fearless and in control. You share a connection with animals that others can only dream of… so long as you don’t become their snack.",
		"bonekeeper":     "You are a shepherd to the departed. You listen to the final whispers of the dead as they descend into the cold, unyielding earth. You know that to fully celebrate the gift of life, we must honor its finale as well.",
		"cutpurse":       "You live in the grey space between those who have power and those who don’t. You find opportunity where others see only chaos. With nimble fingers, you unburden both the richest merchant and the lowliest guard.",
		"fieldwarden":    "Protectors of the harvest, defense against pests, thieves, and beasts. A position of great honor, while it lasts: many guardians do not live out their natural lives. Roll a second time on the Bonds table.",
		"fletchwind":     "You strike from afar, but that does not make you a coward. You are a musician, the song of your bowstring nought but a warning, singing the silent promise of a quick death.",
		"foundling":      "An odd birthmark, a strange smell: somehow, the touch of elsewhere still lingers. You’ll never fit in, at least not where you’re at. Roll on the Omens table, but keep the results private for now.",
		"fungal forager": "You follow the whisperings of the deep earth, the rhythmic pulse of the mycelium forest that grows beneath the surface. The dark holds no terror for you. Also, you really love mushrooms.",
		"greenwise":      "You delve deep into The Woods, prying its secrets from between rough boughs and whispering leaves. In this verdant kingdom, you are no mere scholar, but its confidant as well.",
		"half witch":     "Born of both the mortal world and the unseen, a crossing of veils that makes you an enigma to many. You are both a conduit and a caution of what happens when two worlds collide.",
		"hexenbane":      "You are a mere digit on the unerring hand of justice. You go where others fear to tread, unyielding and unbroken.",
		"jongleur":       "What inspires the soul more than song, words, and spectacle? Why practice for years to master the arcane when you’ve already got real magic inside?",
		"kettlewright":   "You are known by the smell of molten metal and the jingle of tin. You are not a mere merchant, but an artisan of fire and metal.",
		"marchguard":     "Bound by blood Oath to patrol the border and protect the realm. Once sworn, the Oath cannot be broken. The Guard always finds its own.",
		"mountebank":     "Wits are your sharpest weapon, a facade your strongest shield. But when you do lose, you lose badly.",
		"outrider":       "Your coin comes from escorting caravans, tracking fugitives, or lending your blade to a cause. You’ve been a savior, an executioner, a hero, and even a villain. Yours is not a solitary path, however: you’ll always have your horse.",
		"prowler":        "You are a specter in the night, a fleeting shadow that slips by its prey, unseen. Each kill a test of cunning and animal determination, a contest between life and death. You know that one day you will lose. You look forward to it.",
		"rill runner":    "You sing the stories of rivers and lakes, your talents soothing friends and the elements alike. You’ve seen more than most, but somehow it never seems to be enough.",
		"scrivener":      "You copy ancient texts and illuminate manuscripts, recording the voices of the clever, the great, and the powerful. You will prove that the pen truly is mightier than the sword.",
	}

	backgroundGear = map[string][]string{
		"aurifex": {
			"Lantern",
			"Oil can (6 uses)",
			"Needle-knife (d6)",
			"Protective gloves (petty)",
		},
		"barber-surgeon": {
			"Bonesaw (d6)",
			"Bandages (3 uses)",
			"Leech (restores 1 STR, 3 uses)",
			"Stained medical finery (petty)",
		},
		"beast handler": {
			"Leather whip (d6)",
			"Soporific darts (STR save or fall asleep, 6 uses)",
			"Lure",
			"Rope (25ft)",
		},
		"bonekeeper": {
			"Lantern",
			"Oil can (6 uses)",
			"Stake (d6)",
			"Chains (10ft)",
		},
		"cutpurse": {
			"Twin daggers (d6+d6, bulky)",
			"Padded leather (1 Armor)",
			"Lockpicks",
			"Black outfit (petty)",
		},
		"fieldwarden": {
			"Brigandine (1 Armor, bulky)",
			"Bow (d6, bulky)",
			"Hand axe (d6)",
			"Repellent (state the creature, 3 uses)",
		},
		"fletchwind": {
			"Serrated knife (d6)",
			"Boiled leather (1 Armor)",
			"Wooden sight (petty)",
			"Heartroot Salve (recover 1d4 STR)",
		},
		"foundling": {
			"Salt pouch",
			"Heirloom amulet (petty, glows in the presence of magic)",
			"Sling (d6)",
			"Dagger (d6)",
		},
		"fungal forager": {
			"Sharpened trowel (d6)",
			"Candle helmet (+1 Armor, dim, 6 uses)",
			"Rope (25ft)",
			"Metal pail",
		},
		"greenwise": {
			"Iron pot",
			"Root knife (d6)",
			"Healing salve (restore 4 STR)",
			"Twine bauble (petty, Ward once per day)",
		},
		"half witch": {
			"Thicket Spellbook",
			"Iron dagger (d6)",
			"Herbs pouch (restore 1 STR, 3 uses)",
			"Ghillie suit",
		},
		"hexenbane": {
			"Vestments of the Order (petty)",
			"Blessed Tinctures",
			"Silver knife (d6)",
			"Crossbow (d8, bulky)",
		},
		"jongleur": {
			"Costume",
			"Simple Instrument (Pipes, Lute, etc.)",
			"Lucky jerkin (1 Armor)",
			"Sling (d6)",
		},
		"kettlewright": {
			"Pincers",
			"Roll of tin",
			"Tent (fits 2)",
			"Hammer (d6)",
		},
		"marchguard": {
			"Lantern",
			"Oil can (6 uses)",
			"Long sword (d10, bulky)",
			"Boiled leather (1 Armor)",
		},
		"mountebank": {
			"Cart (+4 slots, bulky when pulled)",
			"Trick playing cards",
			"Fancy hat (petty)",
			"Cane sword (d6)",
		},
		"outrider": {
			"Long sword (d10, bulky)",
			"Leather jerkin (1 Armor)",
			"Crossbow (d8, bulky)",
			"Spyglass",
		},
		"prowler": {
			"Tarp",
			"Boiled leather (1 Armor)",
			"Short sword (d6)",
			"Spring-loaded trap (4 STR damage)",
		},
		"rill runner": {
			"Water shoes",
			"Brigandine (1 Armor, bulky)",
			"Compass",
			"Dagger (d6)",
		},
		"scrivener": {
			"Quill & Ink",
			"Blank book",
			"Awl (d6)",
			"Badge (petty)",
		},
	}

	backgroundQuestions = map[string][]string{
		"aurifex":        {"What experiment went horribly wrong?", "What alchemical marvel is the product of your latest\ningenuity?"},
		"barber-surgeon": {"How have you “improved” yourself?", "What rare tool is essential to your work?"},
		"beast handler":  {"What creature is your specialty?", "What do creatures of the wild understand that your kind\ndo not?"},
		"bonekeeper":     {"What did you take from the dead?", "What tool was invaluable in your work?"},
		"cutpurse":       {"What was your last big job?", "What helps you steal?"},
		"fieldwarden":    {"What got the better of you?", "What tool saved your life?"},
		"fletchwind":     {"How did you earn your bow?", "What kind of wood is your bow made from?"},
		"foundling":      {"Who took you in?", "What keeps away bad tidings?"},
		"fungal forager": {"What strange fungi did you discover?", "What keeps you sane, even in utter darkness?"},
		"greenwise":      {"How have The Woods failed you?", "What keeps you safe while in The Woods?"},
		"half witch":     {"What did you bring back from the unseelie court?", "What concoction do you carry, and what rare ingredients\ndid you gather to make it?"},
		"hexenbane":      {"To which order do you belong?", "What was your vow?"},
		"jongleur":       {"What happened at your final performance?", "What trinket were you unable to leave behind?"},
		"kettlewright":   {"What is your trade?", "What never fails to get you out of trouble?"},
		"marchguard":     {"Why did you take the Oath?", "What do you carry as proof of your Oath?"},
		"mountebank":     {"How was your fraud exposed?", "What keepsake could always identify you?"},
		"outrider":       {"What personal code or principle do you uphold?", "What breed is your horse?"},
		"prowler":        {"What did you last hunt?", "What tool is always in your pack?"},
		"rill runner":    {"What songs are you best known for?", "What pays your way across the land?"},
		"scrivener":      {"What work did you keep for yourself?", "How do you transcribe sensitive information?"},
	}

	backgroundAnswers = map[string][][]string{
		"aurifex": {
			{
				"There was an explosion, and you lost your sense of smell. Well, almost: you can sniff out gold as a pig does truffles. Take a <b>Tin of Snuff</b> to dampen the impact. Without it you are <i>deprived</i>.",
				"You dematerialized a beloved pet. Now it follows you around, invisible but always present. Although it cannot interact with the physical realm, you are able to share its senses (add a <b>Fatigue each time</b>). It follows basic commands.",
				"You were exposed to a long-acting truth serum whose effects have yet to wear off. The disorder has its advantages: you cannot repeat lies you’ve heard, either.",
				"You were adept at creating fake gold, which is almost as good. Eventually, your ruse was discovered and you had to make a hasty retreat. Take a heavy <b>Metal Ingot</b> and <b>Gold Powder</b>.",
				"Your recipe worked, but a rival stole the blueprint before your claims could be proven. Take a prototype <b>Blunderbuss</b> (d12, <i>blast</i>, <i>bulky</i>) and a taste for revenge.",
				"Ridiculed for discovering how to turn gold into lead, you were a laughing stock. Take a bottle of <b>Universal Solvent</b> (2 uses) that dissolves anything it touches into its constituent parts.",
			},
			{
				"<b>Pyrophoric Gel</b>: A sticky green fluid that catches fire when exposed to air, then burns for 8 hours. Cannot be extinguished.",
				"<b>Blast Sphere</b>: A head-sized iron ball filled with explosive powder that explodes on impact (d12, <i>blast</i>, <i>bulky</i>.)",
				"<b>Aqua Vita</b>: Purifies any liquid, converting it to pure water. Drinking it cures 1d6 STR. 1 use.",
				"<b>Mimic Stone</b>: Records a short phrase that can later be played back.",
				"<b>Spark Dust</b>: Ignites easily and quickly. Useful for starting a fire or as an incendiary device. 3 uses.",
				"<b>Homunculus</b>: A miniature clay replica of yourself that follows your every command to the letter. It hates being enthralled to you and complains bitterly whenever possible. Any damage done to the homunculus is also done to you.",
			},
		},
		"barber-surgeon": {
			{
				"You have a replacement eye that can magnify objects, acts as a telescope, and provides minimal night vision. You cannot wear anything metal on your head, and strong magnets make you deprived.",
				"One foot is mostly metal (kick, d6), and you treat some Tough Terrain as Easy. Carry an Oil Can (6 uses). Without a daily application you are deprived and noisy.",
				"One of your fingers has been swapped, the bone replaced by gold and iron. Take a Hook and a Screwdriver that can attach to the fingertip.",
				"Both ears have been surgically enhanced, tripling your hearing. You can focus on a specific sound at a great distance, such as a conversation. You wear an ear flap to protect against sudden loud noises (WIL save to avoid temporary paralysis).",
				"Your chest is lined with alchemical sigils, toughening the skin (Armor 1). Wearing other metallic armor nullifies the effect.",
				"One arm is fully metal, and comes off at the shoulder. It can be used as a weapon (d8, bulky when not attached) and can move independently if you are within sight of it.",
			},
			{
				"Regrowth Salve: Regrows a body part over the course of a day.",
				"Graftgrub: A small worm that can fuse inanimate objects with parts of the body. 1 use.",
				"Woundwax: Heals wounds from fire or chemicals (restoring full STR), but nothing else. 2 uses.",
				"Quicksilver: A stimulant. Go first in combat, and automatically pass any WIL saves for one hour. Addictive: Save STR or become deprived after 24 hours without it. 4 uses.",
				"Pneuma Pump: Portable iron lungs (bulky). Enables life-saving surgery, or underwater breathing.",
				"Lodestone: Draws out dangerous elements from the body, and acts as a powerful magnetic force.",
			},
		},
		"beast handler": {
			{
				"Arachnids: Take a Quick-Flame Rod and an Oil Can (6 uses). It can destroy a large spider nest in seconds.",
				"Felines: Take a sack of Whiskerwort. Its odor can calm and control even the largest of cats.",
				"Canines: Take a wreath of Wolfsbane and a Large Net. Effective against werewolves as well.",
				"Birds: Take a Warble-Whistle (3 charges). It can imitate any bird call, and can even be used to send simple messages. Recharge: Feed a baby bird as its mother would, then blow.",
				"Rodens: Take a Windpipe that emits a high-pitched sound that only rodents can hear. So long as you play, they will follow. Even to their deaths.",
				"Serpents: Take a Warming Stone that generates an irresistible heat, and a vial of Antitoxin (2 uses).",
			},
			{
				"There is far more to the world than meets the eye. With quiet concentration, you can borrow the senses of a nearby creature of your specialty.",
				"The behavior of beasts is a language in itself. When observing beasts of your specialty, you gain insight into weather patterns and impending disasters.",
				"The pulse of the hunt is a powerful impulse. You have a sense for when predators, even those not of your specialty, are near.",
				"You know some lands intimately. Your chance of becoming lost in a terrain dominated by the beasts of your specialty is reduced by one step (e.g. 4-in-6 becomes 3-in-6).",
				"Nature’s symphony can be heard if you attune to its rhythm. When surrounded by creatures of your specialty they can alert you to approaching danger before it arrives.",
				"Survival is about adaptability. Once per day, you may take on a simple feature from a creature of your speciality (webbed fingers, night vision, etc.). Add a Fatigue each time.",
			},
		},
		"bonekeeper": {
			{
				"A Crow-Shaped Amulet. You can ask a question of the dead, but must add a Fatigue each time.",
				"A mortal wound from a freed revenant. You were healed, but the disfigurement has made you a pariah. You require neither air nor sustenance, but are still subject to pain and death. Trapped between, the dead see you as one of their own.",
				"A Blood Pail (bulky) from a local death-cult. Empty its contents to summon a creature built from items buried below (bones, rocks, pottery, etc). It obeys your command, but if destroyed you permanently lose 1d4 STR. It has 6 HP, 1 Armor, 13 STR, 11 DEX, 4 WIL, shard fists (d8). Recharge: Fill the bucket with the blood of a dying warrior.",
				"A Burial Wagon (+6 slots) from your last job. It came with a stubborn old Donkey (+4 slots, +2 slots if pulling wagon, slow).",
				"The Detect Magic Spellbook, stolen from an ancient library. Your family worked in service to an obscure underworld deity, but you lost your faith. Though exiled, you continue to serve, even as an apostate.<br /><b>Detect Magic:<b /> <i>You can see or hear nearby magical auras.</i>",
				"A Plague Doctor’s Mask, after its owner succumbed to the disease that wiped out everyone you once knew. They should have kept it on.",
			},
			{
				"Manacles: Though old, it’s still effective even against the very strong. You don’t have the key.",
				"Sponge: Supposedly made from the remains of a rare sea creature. It never seems to dry out.",
				"Pulley: Great for moving gravestones, rocks, or even bodies.",
				"Incense: Perfect for rituals, or to keep the flies at bay. Cools the blood.",
				"Crowbar: d6 damage. Sometimes you just need to get the damn thing open!",
				"Repellent: Powerful stuff. Its faded label makes it unclear what it is actually meant to repel, though. Perhaps everything. 3 uses.",
			},
		},
		"cutpurse": {
			{
				"A noble’s summer home. The place was full of fancy wine (+20gp) but not much else. Take Fence Cutters.",
				"A bank (you were caught). You bear a brand only visible by firelight, and anyone that sees the mark can ask you for a beer. Take Retractable Wires.",
				"A guild warehouse. Take a Ladder (bulky, 10ft) and Blinding Powder (1 use).",
				"Moneylender. Someone beat you to the job, but left behind a Scroll of Arcane Eye (petty).",
				"Constable’s quarters. You escaped, but left some friends behind. Take Strong Silk Rope (30ft) and a queasy feeling",
				"A university. You were seen, but not pursued. You still don’t know why. Take Smoke Pellets (3 uses).",
			},
			{
				"Catring: 2 charges. Climb up walls and fall safely. Recharge: Place the ring on a stray cat’s tail.",
				"Gildfinger: 1 charge. A finger glove that mimics any mundane key. Recharge: bundle it with at least 100gp for a night.",
				"Glimpse Glass: 3 charges. A monocle that lets you see through walls or other obstructions. It shatters after the last use.",
				"Sweetwhistle: 1 charge. Listeners hear a soft, familiar voice in the distance that they cannot resist following. Recharge: Lose a dear memory (describe it).",
				"Vagrant’s Veil: 1 charge. Wear it to blend seamlessly into crowds, appearing as a simple pauper. Recharge: Donate the day’s winnings to the poor. Petty",
				"Smokestack Marble: 3 uses. Crush to release a dense cloud of smoke that follows you. Petty.",
			},
		},
		"fieldwarden": {
			{
				"A voracious swarm of pests that swallowed crops and animals alike. With nothing to defend, you left. Take Gale Seed Extract (3 uses). Ingesting one lets you sprint with a speed four times your regular rate. Afterward you add two Fatigue.",
				"A crop spirit, angered by a poor tithing. The fires consumed nearly everything, and afterwards you were able to gather a pouch of Fireseeds (d8, blast, 4 uses).",
				"An antlered, toothy demon that nearly ended you. Take the blood-stained Bone Knife that saved your life (d6). On Critical Damage, its next attack becomes enhanced from contact with blood.",
				"The Withering, a type of stem rot from The Roots. Take a Diseased Crop (6 uses) that quickly decays any plant it touches.",
				"Wolves, or so you thought. You are now a Werewolf [8 HP, 15 STR, 14 DEX, claws (d6+d6) or bite (d8)]. Your WIL remains the same. You can turn at will (once per day) but must make a WIL save to revert. Anyone left alive from your attacks must make a WIL save to avoid infection.",
				"Crop thieves. Not all of them survived, but you were outnumbered. Take a +d4 HP and a Hilted Broadsword (d8).",
			},
			{
				"Bloodvine Whip: d8 damage. On Critical Damage it drains the target’s blood, granting the weapon’s next attack the blast quality",
				"Clatter Keeper: A hand-cranked device that emits a loud noise, frightening away most creatures.",
				"Sun Stick: Provides ample warmth and light for up to one hour. Recharge: Leave in heavy sunlight for a full day. 1 use.",
				"Root Tether: When thrown, binds up to a wolf-sized creature to the soil for a short time.",
				"Greenwhistle: A small flute that calms plants, making passage through areas heavy with plant life a bit easier.",
				"Everbloom Band: A circlet adorned with flowers that never wilt. On taking Critical Damage the flowers dissolve into dust, but you act as if your save succeeded (STR loss still occurs).",
			},
		},
		"fletchwind": {
			{
				"War. If you are first to attack, your bow gains the blast property for the first round.",
				"Falconry. You keep a falcon [3 hp, 5 STR, 16 DEX, 4 WIL, claws (d6+d6), bite (d6)]. It only eats live game.",
				"Hunting. When taking the Supply action your ability to secure Rations increases by one step (e.g. 1d4 becomes 1d6).",
				"Tournaments. Attacks with your bow are enhanced if the target is immobile.",
				"Training. If you are the first to attack, melee attacks against you are impaired until you take STR damage.",
				"Scouting. When taking the Travel action, your presence decreases the chance of getting lost by one step (e.g. 4-in-6 becomes 3-in-6).",
			},
			{
				"Western Yew (d6, bulky). Can be wielded as a blunt weapon (d6). Noisy.",
				"Sessile Oak (d8, bulky). Slams into targets. On Critical Damage something is torn off.",
				"Stone Pine (d6, bulky). Produces one use of Sticky Sap per day. It is highly explosive.",
				"White Ash (d6, bulky). Can be used in place of a shield in melee combat (+1 Armor).",
				"Striped Bamboo (d6). Collapsible, it only requires one slot (but still requires both hands).",
				"Wych Elm (d6, bulky). Protects the bearer from poisons and toxins, so long as they are holding it.",
			},
		},
		"foundling": {
			{
				"An old hunter. You were both quite happy, until it all ended. Take a Weathered Longbow (d8, bulky) and a Leather Jerkin (1 Armor).",
				"A wizened apothecary, who taught you the healing arts but maintained a clinical detachment. Take a Healing Ungent (restores d4 STR).",
				"A druid, who taught you the language of trees. When it came time to leave you took with you only a Gnarled Staff (d8) and the promise that one day you would return.",
				"A gruff blacksmith from a sleepy river town. You were always kept at arm’s length. Now the forge is cold, and you’ve moved on. Take a Smith’s Hammer (d6) and a set of Oft-mended Chain Mail (2 Armor, bulky).",
				"A troupe of traveling entertainers. For a time, they were like family to you. One day you woke up and they were gone with no explanation. Take a Storybook, a Dagger (d6), and some burning questions.",
				"The monks of a secluded forest monastery. When their rules became too strict, and you snuck away. Take a Monk’s Habit (warm, petty) and a Spellbook of Control Plants.",
			},
			{
				"Pipeweed Your good luck charm. Conversations tend to flow more easily after a smoke. 6 uses.",
				"Stink Jar Shattering this jar releases an odor so foul all nearby must make a STR save or immediately vomit. 1 use.",
				"Ivy Worm A green worm often mistaken for a weed. Swallowed whole, it absorbs any toxins or rot in the body before exiting through the usual way.",
				"Dream Stone A smooth blue stone that helps recall dreams more clearly. Overuse can cause dream-addiction.",
				"Drowning Rod A finger-sized wooden stick that doubles in size each time it is fully submerged in water. It does not shrink down again.",
				"Rabbit’s Foot You were wearing it when they found you. They say it is the foot of she who left you, and that it protects you from witch magic.",
			},
		},
		"fungal forager": {
			{
				"Shrieking Trumpet. When exposed to light it screams so loudly that all nearby attacks (including your own) are impaired. 2 uses.",
				"Torch Fungus. When crushed it creates a heatless light for ten minutes. 3 uses.",
				"Murderous Truffle. Pungent, highly toxic, and very rare (worth 50gp to assassins). Illegal pretty much everywhere. 1 use.",
				"Hellcap. Exposure to its aroma causes intense nausea and vomiting. Either way, it clears the room. Bottled (1 use).",
				"Sproutcup. Ingest to shrink down to the size of a mouse (your belongings stay the same size). You return to normal size within the hour, often in fits and starts. 1 use.",
				"Rootflower. A white fungus found only on corpses deep underground. Ingest to restore d6 WIL. You will dream of the dead, and their stories. 1 use.",
			},
			{
				"Glowsnail Casts a soft, bioluminescent light. Feeds on one ration every two days.",
				"Silk Moth Shawl A weatherproof blanket, it can also douse a fire without being damaged.",
				"Milkflower A gentle stimulant. Chewing makes you immune to panic for the next hour. 3 uses.",
				"Luxcompass Hums softly as it moves closer to the Sun. Eventually, the noise becomes unbearably loud.",
				"Sloth-Tarp A tough and weatherproof fabric, useful for hanging off trees. When inside, take +1 Armor.",
				"Miner’s Grease Great for dislodging a gem, tool, or limb from a tight crack. Highly explosive. 3 uses.",
			},
		},
		"greenwise": {
			{
				"An ill-tempered forest spirit cursed you for stealing, marking you as an enemy of their kind. Take a Bezoar Stone. Ingesting it cures any poison (1 use, unless retrieved).",
				"A close friend, swallowed whole. Now you see their face in any tea you brew. Take a Soporific Concoction (3 uses).",
				"You were poisoned, losing your sense of taste and smell. You can now withstand noxious fumes, and always carry antitoxin (2 uses).",
				"Your radical experiments turned your skin green, and you now gain nourishment as a plant. You don’t need Rations, but a day without sufficient sunlight and water leaves you deprived.",
				"Your impressive corpseflower won a local contest, then promptly killed a judge. You fled, but not without the Prize Money (100gp) and a warrant for your arrest.",
				"You created a restorative tincture that also caused accidental infertility. Take a Healing Potion that completely restores STR. Only you know of its unintended side-effects.",
			},
			{
				"Amadou A vermillion fungus that catches fire quite easily. 3 uses.",
				"Delphinium Breathe water for up to one hour. 1 use, but can be divided into fractional doses.",
				"Tacky Stalk A woody reed that hardens into a permanent adhesive when chewed. 2 uses.",
				"Wisp Lantern Caged in wrought iron, provides a dim light so long as the wisp is able to feed on nearby pain and fear.",
				"Seed Bomb A canvas sack that explode on impact, scattering seeds. d6 damage (blast). 3 uses.",
				"Briarvine Entangles any creature up to horse size (STR to break free). Reusable.",
			},
		},
		"half witch": {
			{
				"A Black Rose Fiddle (bulky). Its music causes intense sadness and immobility in nearby mortals (others are merely fascinated). You don’t know how to play.",
				"Paper legs. You are extremely light, and can fall a few stories without getting hurt. Try to avoid tearing them or getting them wet.",
				"A Living Nightmare that dwells within you, but manifests whenever you are in danger. It has your same Attributes and HP, and attacks with claws (d8+d8). It disappears on Critical Damage (take 1d4 WIL damage), re-appearing again on the next full moon.",
				"A Raven Familiar [8 HP, 3 STR, 11 DEX, 13 WIL, beak, (d6)]. It speaks as an intelligent being and is entirely devoted to you.",
				"A Briar Thorn. It can pierce any organic material (quite painfully) but when removed leaves no trace of the intrusion.",
				"A Fae creature’s True Name. Use it to summon its owner for an act of great service, but only once. It could also fetch a hefty price, to the right buyer.",
			},
			{
				"Rebirth Ash Remnants of a bark spirit. Sprinkle to reignite a fire that has died, or return to life a creature that has died only moments before. 3 uses.",
				"Glamour Feather Plume of a firebird. Can make any creature appear convincingly as someone (or something) else. 1 use.",
				"Hawthorn Seed An acorn from the other side, gathered on the spring equinox. When planted it sprouts a luxurious shelter, collapsing at moonrise the next day. 1 use.",
				"Stonetree Sap Sap obtained in exchange for blood. Hardens when rubbed on any surface (+1 Armor). 3 uses.",
				"Nightdust Powder The ritual burning of six owls. When tossed in the air, day turns to night for a short while. 2 uses.",
				"Hex Stone Gathered from a river that flows from the other side. Removed from its iron tin, it can absorb the effects of an active magical effect. If destroyed, the magic is released. 1 use.",
			},
		},
		"hexenbane": {
			{
				"Order of the Crossroads. Take a Pocket Leyfinder. It points to nearby ley lines and other sources of arcane power. If you lose it, the punishment is death.",
				"Order of the Bleeding Star. Take a Star-Iron Mace (d8). It shines faintly in darkness, and becomes very hot in the presence of witchcraft.",
				"Order of the Glass Sigil. Take a short sword (d8) and chainmail (2 Armor, bulky). You have contacts in most towns (the more rural, the better) willing to provide aid, food, or even weapons.",
				"Order of the Blank Eye. Take a Voidglass Shard. Peer through it to see invisible marks, creatures, and other magical effects. Lose the use of your eye for an hour afterwards (you are deprived).",
				"Order of Canaas. Once per day you can change into a wolf. Take a Quicksilver Chain. Without it, you are unable to shift back.",
				"Order of the Silent Veil. Take a Quell Stone (2 uses) wrapped in burlap. Extinguishes any nearby flames once exposed to air.",
			},
			{
				"Honesty. Choose a weapon type (blunt, blade, etc). Attacks against you of this type are impaired. If your vow is broken, you lose d4 WIL.",
				"Poverty. You carry the Disassemble Spellbook. Only you can use it. If your vow is broken, it explodes (d12 STR damage).",
				"Selflessness. You are immune to mind-altering magical effects, such as charm, hatred, frenzy, and so on. If you break this vow, you lose d6 WIL.",
				"Mercy. Choose a weapon type (blunt, blade, etc). Attacks with this weapon are enhanced. If your vow is broken, you can never use that weapon type again.",
				"Charity. Once per day you can shrug off a Fatigue. If your vow is ever broken, you permanently lose one inventory slot.",
				"Valor. The first time you inflict Critical Damage you receive d4 HP, returning to the previous limit at the end of combat. If your vow is broken, you die.",
			},
		},
		"jongleur": {
			{
				"Despite your training in the deadly arts, an actor died and you were blamed. Take a light-weight Rapier (d6) and a false identity.",
				"The crowd loved your catchy tune about a noble and his romantic failings. The noble in question, not so much. Take the Read Mind Spellbook and a warrant for your arrest.",
				"Your debut composition reduced the audience to a gibbering mess, murmuring of bright creatures descending from the night sky. Later you noticed that the notes resembled stellar constellations. Take a Book On Astronomy, and a lot of questions.",
				"You mocked a forgotten trickster god, and were cursed for it. You speak only in perfect rhyme. Ironically, this has only made you more popular among your peers. Take a Thesaurus (20gp). Without it you are deprived.",
				"You were scarred in an on-stage accident. The crowd cheered, thinking it was part of the act. Take well-worn Stage Mail (1 Armor), a memorable scar, and a fear of applause.",
				"Your respectable puppeteering skills were matched only by your mimicry. You were so good you were branded a witch (literally) and banished. Take an Uncanny Hand-Puppet and a Rabbit Skull (petty, sewn with grass) that protects against charms.",
			},
			{
				"False Cuffs Comfortable, realistic-looking cuffs. Only you know the trick to get out of them.",
				"Pocket Theatre A set of small puppets and folding stage. Good for quick distractions.",
				"Ghost Violin A dark grey violin that plays a haunting tune, mirrored by an invisible, distant twin.",
				"Tragic Tales Banned in proper company, it becomes less bawdy and more harrowing towards the end. Worth 100gp.",
				"Mythos Mask A plaster mask that allows one to take on a monster’s countenance. Once it comes off, add a Fatigue.",
				"Rebreak Glass A wine flute that can be broken multiple times, reforming after 24 hours. Makes a really loud noise.",
			},
		},
		"kettlewright": {
			{
				"Your family has a long tradition of serving, and you were trained from an early age on how to survive in the wild. When taking the Supply action your yield increases by one step (e.g. 1d4 > 1d6).",
				"As a convict, the Oath was simply a means of avoiding punishment. Take Lockpicks, and the key to a safehouse (petty).",
				"Noble-born, you joined to escape family trouble. Take a Goosefelt Tarp (fits two) that you stole before leaving home.",
				"When your family lost everything, you took the Oath to avoid becoming a burden. Take extra Rations (3 uses) and a brace of Throwing Knives (d6).",
				"Your life was saved by a member of the Marchguard, and you were inspired to join their ranks. Take a Snare Trap and a Sketchbook filled with detailed drawings.",
				"You were in a dark place, and decided that your life needed a little direction. You’re still not so sure it was the right choice. Take an Oilskin Coat and Mapping Paper.",
			},
			{
				"Impressive Pin A metal badge of honor from the Guard. It can open doors, but leaves a trail. Petty.",
				"Oath Compass Points not towards North, but instead to the nearest member of the Guard. It also lets you know when they’re getting close.",
				"Pullstones Two jet-black stones. When separated, the stones will always roll in the direction of the other.",
				"Fireflask Highly alcoholic, yet strangely delicious. When thrown creates a wall of flames 10ft high that burns out after a few minutes. 1 use.",
				"Pain Band Touch an injured creature to transfer their wounds to you (exchange their lost STR with your own). Recharge: Wear the ring while in perfect health. It will take 1 STR, permanently. Petty.",
				"Poacher’s Woe Strongly-scented arrows (3 uses). The scent is powerful enough to track with ease.",
			},
		},
		"marchguard": {
			{
				"Your family has a long tradition of serving, and you were trained from an early age on how to survive in the wild. When taking the Supply action your yield increases by one step (e.g. 1d4 > 1d6).",
				"As a convict, the Oath was simply a means of avoiding punishment. Take Lockpicks, and the key to a safehouse (petty).",
				"Noble-born, you joined to escape family trouble. Take a Goosefelt Tarp (fits two) that you stole before leaving home.",
				"When your family lost everything, you took the Oath to avoid becoming a burden. Take extra Rations (3 uses) and a brace of Throwing Knives (d6).",
				"Your life was saved by a member of the Marchguard, and you were inspired to join their ranks. Take a Snare Trap and a Sketchbook filled with detailed drawings.",
				"You were in a dark place, and decided that your life needed a little direction. You’re still not so sure it was the right choice. Take an Oilskin Coat and Mapping Paper.",
			},
			{
				"Impressive Pin A metal badge of honor from the Guard. It can open doors, but leaves a trail. Petty.",
				"Oath Compass Points not towards North, but instead to the nearest member of the Guard. It also lets you know when they’re getting close.",
				"Pullstones Two jet-black stones. When separated, the stones will always roll in the direction of the other.",
				"Fireflask Highly alcoholic, yet strangely delicious. When thrown creates a wall of flames 10ft high that burns out after a few minutes. 1 use.",
				"Pain Band Touch an injured creature to transfer their wounds to you (exchange their lost STR with your own). Recharge: Wear the ring while in perfect health. It will take 1 STR, permanently. Petty.",
				"Poacher’s Woe Strongly-scented arrows (3 uses). The scent is powerful enough to track with ease.",
			},
		},
		"mountebank": {
			{
				"Your “patients” kept reporting miraculous recoveries, despite your lack of training. Start with Bandages (3 uses) and a knack for healing.",
				"After seducing a wealthy patron, their family hired a criminal gang to retrieve you. You got away and need to lay low. Start with Beauty Cream, 2 uses. Apply to appear irresistibly beautiful for the next 12 hours.",
				"You were a peddler of fake prophesies, but when one turned out to be true, it drew unwanted attention. Roll on the Omens table, but keep the result to yourself. Start with a Knife (d6) hidden in your boot.",
				"Your latest stunt destroyed a priceless artifact and injured a dozen bystanders. Start with a Captain’s Uniform (petty), a Ceremonial Sword (harmless, 60gp), and a Bouquet of Flowers.",
				"You were cursed by a hedgewitch for fooling some innocent village folk. Magic acts unpredictably in your hands (WIL save to avoid disaster). If you are the target of magic, the same applies to its wielder.",
				"Your “seances” with the dead were in actuality a ruse involving a cleverly hidden spellbook of Auditory Illusion. Inevitably, a patron discovered your secret. Start with the Spellbook and a bundle of scarves.",
			},
			{
				"Royal Crest Born into royalty, you chose a different life. The crest grants you access, but also alerts your family of your whereabouts.",
				"Miracle Oil A smelly concoction that is also very, very, slippery. 2 uses.",
				"Surgeon’s Soap A lye and ash block that makes skin temporarily transparent, revealing the anatomy within. 4 uses.",
				"Goat Powder Derived from the placenta of a baby goat. Temporarily cures any affliction, but symptoms return within hours.",
				"Cursed Sapphire Worth 200gp, it noticeably returns to your pocket shortly after you spend it. You can’t seem to get rid of it.",
				"Alchemical Tattoo A dog, cat, or bird that can leave your body on demand. It follows your commands to the best of its abilities, and can pass its injuries (as STR loss) back onto you.",
			},
		},
		"outrider": {
			{
				"No innocent blood: No bystander will come to harm on your watch. Take a Steadymade Buckler (+1 Armor). While holding this shield you cannot be moved so long as both feet are planted on firm ground.",
				"Revere the tools of death: Weapons are to be respected and maintained. Take a Wyrmbone Whetstone. Following a half hour ritual sharpening, attacks with the weapon are enhanced until STR damage is dealt.",
				"To the death, always: You never back down from a fight, no matter the odds. Take a Death-Whistle, 1 charge. Its scream frightens away all who hear it (save WIL or flee). Recharge: Capture the final breath of a dying warrior.",
				"Revere the Dead: Death is a journey we all take, and it deserves respect. Take an extra 30gp. You always place two gold pieces on the eyelids of a slain foe. Somehow, you always find the coin.",
				"Loyalty to the work: Your word is your bond. Once you’ve accepted a job, you see it through to the end. Take a weathered Tally Stick. Once a vow is marked unto its face, the stick hardens (d8) until it is complete. The stick will snap in half if the vow is ever broken.",
				"Always pay your debts: You always repay what you owe, whether in coin or in kind. You expect nothing less from all others. Take a Blacked-Out Ledger, then roll a second time on the Bonds table.",
			},
			{
				"Heavy Destrier A beast built for war; an imposing creature. 8 HP, 1 Armor, hooves (d10+d10), +2 slots.",
				"Blacklegged Dandy Hardy and adaptable, Tough or Perilous terrain are one step easier. 6 HP. +4 slots.",
				"Rivertooth Impressively strong, capable of carrying heavy loads. 4 HP. +6 slots (+2 if carrying two people).",
				"Piebald Cob Intelligent, it can understand simple commands, and even has an instinct for danger. 6 HP. +4 slots.",
				"Linden White Highly trained and agile, it can perform intricate maneuvers in a time of need (no DEX save to flee). +3 slots.",
				"Stray Fogger Wild, but very fast (even in Tough terrain). Rides light. 4 HP. +2 slots.",
			},
		},
		"prowler": {
			{
				"A mock firefly, baiting water carriers with its glowing lure. Take an Alchemical Limb (d8) to replace the one it tore off. It works as well as the real thing, and is immune to poison, fire, and heat. Sometimes it jams.",
				"An ice nettle, trapping and draining sheep. You lost your commission when the fungus you introduced killed half the flock. Take a Rime Seed (1 use). It freezes any body of water, no matter the size. Don’t eat it.",
				"A silver marsh crawler that killed someone close to you. You now carry its Tooth (petty) on a chain around your neck as a warning to others of its kind. The tooth hums softly when something is stalking you.",
				"A malicious forest spirit that poisoned a homestead. You saved a Heartseed from the roots of a dying tree (plant to create a a new forest). Also, take Iron Bracers (+1 Armor, bulky).",
				"A hollow wolf that had been frightening travellers. You took pity on the half-starved creature, and nursed it back to health. Now it is loyal to you unto death. It is also a great tunneler. 5 HP, 11 STR, 13 DEX, 8 WIL, teeth (d6).",
				"An azure warbler. The gametes attract a sizeable profit, if properly extracted. You succeeded, but left its nest to the wolves. Take a Paring Knife (d6), an extra 20gp, and a pang of regret.",
			},
			{
				"Fermented Spirits Keeps you warm at the best of times, and as an explosive at the worst. 3 Uses.",
				"Trail Shaker A noisy instrument that reveals nearby trails, even when deeply hidden.",
				"Drowse Balm A wax bar. If boiled in water, the steam acts as a soporific agent.",
				"Spike and Cord For traversing or securing difficult terrains, or for creating makeshift traps and structures.",
				"Iron Rattle A noisemaker for distracting or scaring your quarry. Sounds convincingly like a snake.",
				"Hardening Glue Makes any flat material (cloth, leather, sand) as hard as stone. Expensive (20gp a bottle, 3 uses).",
			},
		},
		"rill runner": {
			{
				"The Tinker’s Two-Step. A humorous fairy tale about a gift-giving traveler. Start with a Reed Whistle. Anyone in earshot must pass a WIL save to perform an act of violence.",
				"The Sylph and Her Lover. A bawdy tale of lost love. Start with a Breeze Knot (3 charges). Creates a strong breeze. Recharge: Tie it to a mast during a storm.",
				"Harper’s Devotion. A sad, short tale about a musician that falls in love with a star. Start with a Celestial Lute. Reveals the constellations above, no matter the weather.",
				"The Reed Fisher. A celebrated song about a massive carp that always seems to get away. Begin with a spool of River Twine (5 uses). Each dip into the river guarantees a catch, though it might not be pleasant.",
				"Song of the Silver Stream. A wordless lullaby that mimics flowing water. Take a Stone Flute that can calm almost any river.",
				"The Thrush and the Meadow. A moody tale told in alternating chorus. Start with a Feather Quill (1 use, petty). A map drawn with this quill reveals the most expedient course between any two points.",
			},
			{
				"Performance Performing at taverns always yields both room and board. Sometimes you even get tips! Start with an extra 10gp.",
				"Bodyguard You are a protector for those afraid to travel alone. Start with a Rapier (d8).",
				"Wares You buy low and sell high, always making just enough to get by. Take a single item worth 20gp (or less) from the gear table.",
				"Transport You deliver “delicate” packages throughout the lands. You have at least one contact in any major town.",
				"Sailor’s Friend Whether water, wind, or sail, your aid brings ships to their destination. For you, passage is always free.",
				"Guide You shepherd caravans and travelers across water-soaked lands. Start with an extra 10gp and a map (petty) relevant to your next journey.",
			},
		},
		"scrivener": {
			{
				"The Wild Tongue. A bundle of leather-bound scrolls. A seminal work, cataloging the hidden languages of beasts, and how to understand them.",
				"The Silent Symphony. Bound in fluorescent wrap. Very rare, it chronicles the subtle signs used by those employing invisibility magic.",
				"A Treatise on the Abyss. A non-descript black book. An in-depth, largely theoretical text describing The Roots, as well as information around the location of a nearby Gate.",
				"The Star Waltz. A comet-shaped clasp embracing a fine leather cover. Detailed astronomical charts, celestial movements, and stellar festivals. Highly valued (100gp) for its usefulness to travelers.",
				"The Cathedral and the Canopy. Large-leaf binding over vellum. Nominally a children’s storybook, the margins detail information about traveling, eating, and sleeping in the cloud forests.",
				"Garden of Glass. Bound in the cover of another book. A heretical work, it describes the materials, procedures, and optimal locations required to open a Gate.",
			},
			{
				"Fib Ink Glows when used to write true statements, but fades if used to write false ones.",
				"Cipher Stone A pair of sharp black stones. Decrypts any message written by the other.",
				"Everquill A quill that writes on any surface. You still need ink. Petty.",
				"Whisper Vial Whisper a message into the vial and it will play back to whomever opens it next.",
				"Voyeur’s Suringa Extracts blood from a target without their knowledge. A stolen drop placed on the eye reveals memories from the past day.",
				"Echo Leaf A blank parchment. Whomever unfurls it sees their actions of the day slowly revealed in a tight scrawl. Petty.",
			},
		},
	}
)
